# Generated by Django 3.0.4 on 2020-03-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(choices=[(1, 'Two'), (2, 'Three'), (3, 'Four'), (4, 'Five'), (5, 'Six'), (6, 'Seven'), (7, 'Eight'), (8, 'Nine'), (9, 'Ten'), (10, 'Jack'), (11, 'Queen'), (12, 'King'), (13, 'Ace')])),
                ('suit', models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')])),
            ],
        ),
    ]
